<?php

namespace Database\Seeders;

use App\Models\Dealer;
use Illuminate\Database\Seeder;

class DealerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dealers = [
            // First set of dealers
            [
                'business_name' => 'Aaryak Energitx',
                'contact_person' => 'Aaryak Energitx',
                'email' => 'aaryak.energitx@example.com',
                'phone' => '7004553288',
                'alternate_phone' => null,
                'type' => 'distributor',
                'address' => '2nd floor Rameshwar Bhawan Opp. Minakshi Cinema, Rani Sati Mandir Lane',
                'city' => 'Ranchi',
                'state' => 'Jharkhand',
                'pincode' => '834001',
                'gst_number' => null,
                'pan_number' => null,
                'business_description' => 'Distributor of Ligen Power® products in Jharkhand',
                'website' => null,
                'status' => 'active',
            ],
            [
                'business_name' => 'Amber Enterprises',
                'contact_person' => 'Amber Enterprises',
                'email' => 'amber.enterprises@example.com',
                'phone' => '9434203576',
                'alternate_phone' => null,
                'type' => 'dealer',
                'address' => 'Minhaj Nagar Phulwari Sharif',
                'city' => 'Patna',
                'state' => 'Bihar',
                'pincode' => '801505',
                'gst_number' => null,
                'pan_number' => null,
                'business_description' => 'Dealer of Ligen Power® inverters and BMS systems',
                'website' => null,
                'status' => 'active',
            ],
            [
                'business_name' => 'Amossys Digital PVT LTD',
                'contact_person' => 'Amossys Digital',
                'email' => 'amossys.digital@example.com',
                'phone' => '9234106597',
                'alternate_phone' => null,
                'type' => 'distributor',
                'address' => '5TH FLOOR SAI PLACE, Bhalubasa',
                'city' => 'Jamshedpur',
                'state' => 'Jharkhand',
                'pincode' => '831009',
                'gst_number' => null,
                'pan_number' => null,
                'business_description' => 'Distributor of Ligen Power® products in Jamshedpur',
                'website' => null,
                'status' => 'active',
            ],
            [
                'business_name' => 'Bablu Auto Electricals',
                'contact_person' => 'Bablu Auto Electricals',
                'email' => 'bablu.auto@example.com',
                'phone' => '8235945544',
                'alternate_phone' => null,
                'type' => 'dealer',
                'address' => 'OPP.Tiwari Bechar Petrol Pump',
                'city' => 'Patna',
                'state' => 'Bihar',
                'pincode' => '800001',
                'gst_number' => null,
                'pan_number' => null,
                'business_description' => 'Auto electrical dealer specializing in Ligen Power® products',
                'website' => null,
                'status' => 'active',
            ],
            [
                'business_name' => 'Cool Breeze Consultancy Private',
                'contact_person' => 'Cool Breeze Consultancy',
                'email' => 'msrajan1508@gmail.com',
                'phone' => '9884810971',
                'alternate_phone' => null,
                'type' => 'distributor',
                'address' => '128 first floor sharan Complex Puzhal main road Pudur',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600053',
                'gst_number' => null,
                'pan_number' => null,
                'business_description' => 'Distributor of Ligen Power® products in Tamil Nadu',
                'website' => null,
                'status' => 'active',
            ],
            [
                'business_name' => 'Lakxmi Enterprises',
                'contact_person' => 'Lakxmi Enterprises',
                'email' => 'lakxmi.enterprises@example.com',
                'phone' => '7992316145',
                'alternate_phone' => null,
                'type' => 'dealer',
                'address' => 'Radhika Complex, Main Road AG Colony',
                'city' => 'Patna',
                'state' => 'Bihar',
                'pincode' => '800023',
                'gst_number' => null,
                'pan_number' => null,
                'business_description' => 'Dealer of Ligen Power® inverters and battery systems',
                'website' => null,
                'status' => 'active',
            ],
            [
                'business_name' => 'Nayuni Energies',
                'contact_person' => 'Nayuni Energies',
                'email' => 'nayuni.energies@example.com',
                'phone' => '9701555309',
                'alternate_phone' => null,
                'type' => 'distributor',
                'address' => '51/21 GANGISETTY STREET NEAR PRATHIBA COLLEGE Kothapeta',
                'city' => 'Rayachoti',
                'state' => 'Andhra Pradesh',
                'pincode' => '516269',
                'gst_number' => null,
                'pan_number' => null,
                'business_description' => 'Distributor of Ligen Power® products in Andhra Pradesh',
                'website' => null,
                'status' => 'active',
            ],
            [
                'business_name' => 'New Sark Electronics',
                'contact_person' => 'New Sark Electronics',
                'email' => 'newsark.electronics@example.com',
                'phone' => '9835141452',
                'alternate_phone' => null,
                'type' => 'distributor',
                'address' => 'Ramlila Maidan Hindu Line Sakchi',
                'city' => 'Jamshedpur',
                'state' => 'Jharkhand',
                'pincode' => '831001',
                'gst_number' => null,
                'pan_number' => null,
                'business_description' => 'Electronics distributor specializing in Ligen Power® products',
                'website' => null,
                'status' => 'active',
            ],
            [
                'business_name' => 'Shrimate Powers',
                'contact_person' => 'Shrimate Powers',
                'email' => 'shrimate.powers@example.com',
                'phone' => '7992406010',
                'alternate_phone' => null,
                'type' => 'distributor',
                'address' => 'Srikanth Nagar Jakariyapur',
                'city' => 'Patna',
                'state' => 'Bihar',
                'pincode' => '800007',
                'gst_number' => null,
                'pan_number' => null,
                'business_description' => 'Power solutions distributor for Ligen Power® products',
                'website' => null,
                'status' => 'active',
            ],
            [
                'business_name' => 'Shubham Enterprises',
                'contact_person' => 'Shubham Enterprises',
                'email' => 'shubham.enterprises@example.com',
                'phone' => '7004567705',
                'alternate_phone' => null,
                'type' => 'dealer',
                'address' => 'Mithapur Road, Old Busstand',
                'city' => 'Patna',
                'state' => 'Bihar',
                'pincode' => '800001',
                'gst_number' => null,
                'pan_number' => null,
                'business_description' => 'Dealer of Ligen Power® inverters and BMS systems',
                'website' => null,
                'status' => 'active',
            ],
            [
                'business_name' => 'SS Power Solutions',
                'contact_person' => 'SS Power Solutions',
                'email' => 'ss.power@example.com',
                'phone' => '9986575911',
                'alternate_phone' => null,
                'type' => 'dealer',
                'address' => '4-6, Opp.Sericulture Office, B\'lore Road',
                'city' => 'Madanapalli',
                'state' => 'Andhra Pradesh',
                'pincode' => '517325',
                'gst_number' => null,
                'pan_number' => null,
                'business_description' => 'Power solutions dealer for Ligen Power® products',
                'website' => null,
                'status' => 'active',
            ],
            [
                'business_name' => 'SSB Group',
                'contact_person' => 'SSB Group',
                'email' => 'ssb.group@example.com',
                'phone' => '9632422953',
                'alternate_phone' => null,
                'type' => 'distributor',
                'address' => 'Door No:130h/130 Ward No-4 Vidya Nagara, Kengavvana Thota, Bengaluru Road',
                'city' => 'Kudligi Town',
                'state' => 'Karnataka',
                'pincode' => '583135',
                'gst_number' => null,
                'pan_number' => null,
                'business_description' => 'Distributor of Ligen Power® products in Karnataka',
                'website' => null,
                'status' => 'active',
            ],
        ];

        foreach ($dealers as $dealer) {
            Dealer::create($dealer);
        }
    }
}
